when:
    - event: push
      branch: main

steps:
    - name: build
      image: debian
      commands:
          - echo "This is the build step"
          - echo "binary-data-123" > executable
    - name: a_test_step
      image: "golang: 1.16"
      commands:
          - echo "Testing..."
          - ./executable