when:
    - event: push
      branch: main

steps:
    - name: build
      image: debian
      commands:
          - echo "This is the build step"
          - echo "Greetings from Woodpecker CI!" > message.txt
    - name: a_test_step
      image: "golang:1.16"
      commands:
          - echo "Testing..."
          - cat ./message.txt